/**
 * CineDrive Backend Setup Script
 * 
 * This script automates the complete backend setup process:
 * 1. Checks Node.js version (>= 18)
 * 2. Installs npm dependencies
 * 3. Creates .env file if missing (with user prompts)
 * 4. Tests MySQL connection
 * 5. Runs database migrations (ALTER TABLE)
 * 6. Seeds sample movie data if empty
 * 7. Starts the server
 * 
 * Run: node backend/setup.js
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');
const readline = require('readline');

// Color codes for terminal output
const colors = {
    reset: '\x1b[0m',
    green: '\x1b[32m',
    red: '\x1b[31m',
    yellow: '\x1b[33m',
    blue: '\x1b[36m',
    bold: '\x1b[1m',
    magenta: '\x1b[35m'
};

// Utility functions
function printHeader(title) {
    console.log(`\n${colors.blue}${colors.bold}${'='.repeat(70)}${colors.reset}`);
    console.log(`${colors.blue}${colors.bold}  ${title}${colors.reset}`);
    console.log(`${colors.blue}${colors.bold}${'='.repeat(70)}${colors.reset}\n`);
}

function printSuccess(message) {
    console.log(`${colors.green}✅ ${message}${colors.reset}`);
}

function printError(message) {
    console.log(`${colors.red}❌ ${message}${colors.reset}`);
}

function printWarning(message) {
    console.log(`${colors.yellow}⚠️  ${message}${colors.reset}`);
}

function printInfo(message) {
    console.log(`${colors.blue}ℹ️  ${message}${colors.reset}`);
}

function printStep(step, message) {
    console.log(`${colors.magenta}${colors.bold}[Step ${step}]${colors.reset} ${message}`);
}

// Create readline interface for user input
const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

function prompt(question) {
    return new Promise(resolve => {
        rl.question(question, answer => {
            resolve(answer.trim());
        });
    });
}

// Step 1: Check Node.js version
function checkNodeVersion() {
    printStep(1, 'Checking Node.js version...');
    
    const nodeVersion = process.version;
    const majorVersion = parseInt(nodeVersion.split('.')[0].substring(1));
    
    printInfo(`Current Node.js version: ${nodeVersion}`);
    
    if (majorVersion >= 18) {
        printSuccess(`Node.js version ${nodeVersion} meets requirements (>= 18)`);
        return true;
    } else {
        printError(`Node.js version ${nodeVersion} is too old!`);
        printError('Please upgrade to Node.js 18 or higher');
        printInfo('Download from: https://nodejs.org/');
        return false;
    }
}

// Step 2: Install npm dependencies
function installDependencies() {
    printStep(2, 'Installing npm dependencies...');
    
    const packageJsonPath = path.join(__dirname, 'package.json');
    
    if (!fs.existsSync(packageJsonPath)) {
        printError('package.json not found!');
        return false;
    }
    
    try {
        printInfo('Running: npm install...');
        printWarning('This may take a few minutes...');
        
        execSync('npm install', {
            cwd: __dirname,
            stdio: 'inherit'
        });
        
        printSuccess('All dependencies installed successfully');
        return true;
    } catch (error) {
        printError('Failed to install dependencies');
        console.error(error.message);
        return false;
    }
}

// Step 3: Create .env file if missing
async function createEnvFile() {
    printStep(3, 'Checking .env configuration...');
    
    const envPath = path.join(__dirname, '.env');
    
    if (fs.existsSync(envPath)) {
        printSuccess('.env file already exists');
        return true;
    }
    
    printWarning('.env file not found! Creating new configuration...');
    console.log('');
    
    // Prompt for database credentials
    const dbHost = await prompt(`${colors.blue}Database Host${colors.reset} [localhost]: `) || 'localhost';
    const dbUser = await prompt(`${colors.blue}Database User${colors.reset} [root]: `) || 'root';
    const dbPassword = await prompt(`${colors.blue}Database Password${colors.reset} [press Enter for empty]: `) || '';
    const dbName = await prompt(`${colors.blue}Database Name${colors.reset} [sinhbtve_cinedrive]: `) || 'sinhbtve_cinedrive';
    const port = await prompt(`${colors.blue}Server Port${colors.reset} [3000]: `) || '3000';
    
    // Create .env content
    const envContent = `# CineDrive Backend Configuration
# Generated by setup.js on ${new Date().toISOString()}

# Database Configuration
DB_HOST=${dbHost}
DB_USER=${dbUser}
DB_PASSWORD=${dbPassword}
DB_NAME=${dbName}

# Server Configuration
PORT=${port}
NODE_ENV=development

# Facebook Authentication (Optional - for video scraping)
# FB_C_USER=
# FB_XS=
# FB_USER_AGENT=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
`;
    
    try {
        fs.writeFileSync(envPath, envContent, 'utf8');
        printSuccess('.env file created successfully');
        console.log('');
        return true;
    } catch (error) {
        printError(`Failed to create .env file: ${error.message}`);
        return false;
    }
}

// Step 4: Test MySQL connection
async function testMySQLConnection() {
    printStep(4, 'Testing MySQL connection...');
    
    // Load environment variables
    require('dotenv').config();
    
    const mysql = require('mysql2/promise');
    
    try {
        const connection = await mysql.createConnection({
            host: process.env.DB_HOST || 'localhost',
            user: process.env.DB_USER || 'root',
            password: process.env.DB_PASSWORD || '',
            database: process.env.DB_NAME || 'sinhbtve_cinedrive'
        });
        
        printSuccess('MySQL connection successful');
        printInfo(`Connected to: ${process.env.DB_NAME}@${process.env.DB_HOST}`);
        
        await connection.end();
        return true;
    } catch (error) {
        printError('MySQL connection failed!');
        console.error(`${colors.red}Error: ${error.message}${colors.reset}`);
        
        if (error.code === 'ECONNREFUSED') {
            printWarning('MySQL server is not running');
            printInfo('Start XAMPP and ensure MySQL service is running');
        } else if (error.code === 'ER_ACCESS_DENIED_ERROR') {
            printWarning('Access denied - check your database credentials');
            printInfo('Edit backend/.env file with correct credentials');
        } else if (error.code === 'ER_BAD_DB_ERROR') {
            printWarning(`Database "${process.env.DB_NAME}" does not exist`);
            printInfo('Create the database first or check the database name');
        }
        
        return false;
    }
}

// Step 5: Run database migrations
async function runMigrations() {
    printStep(5, 'Running database migrations...');
    
    require('dotenv').config();
    const mysql = require('mysql2/promise');
    
    try {
        const connection = await mysql.createConnection({
            host: process.env.DB_HOST || 'localhost',
            user: process.env.DB_USER || 'root',
            password: process.env.DB_PASSWORD || '',
            database: process.env.DB_NAME || 'sinhbtve_cinedrive'
        });
        
        // Check if columns already exist
        const [columns] = await connection.query(`
            SELECT COLUMN_NAME 
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = ? 
            AND TABLE_NAME = 'movies' 
            AND COLUMN_NAME IN ('cached_video_url', 'url_expires_at')
        `, [process.env.DB_NAME]);
        
        if (columns.length === 2) {
            printInfo('Migration columns already exist - skipping');
            await connection.end();
            return true;
        }
        
        printInfo('Adding cache columns to movies table...');
        
        // Add cached_video_url column if missing
        if (!columns.find(col => col.COLUMN_NAME === 'cached_video_url')) {
            await connection.query(`
                ALTER TABLE movies 
                ADD COLUMN cached_video_url VARCHAR(512) NULL AFTER video_url
            `);
            printSuccess('Added column: cached_video_url');
        }
        
        // Add url_expires_at column if missing
        if (!columns.find(col => col.COLUMN_NAME === 'url_expires_at')) {
            await connection.query(`
                ALTER TABLE movies 
                ADD COLUMN url_expires_at DATETIME NULL AFTER cached_video_url
            `);
            printSuccess('Added column: url_expires_at');
        }
        
        // Add index for better performance
        try {
            await connection.query(`
                CREATE INDEX idx_expires_at ON movies(url_expires_at)
            `);
            printSuccess('Added index: idx_expires_at');
        } catch (error) {
            if (error.code === 'ER_DUP_KEYNAME') {
                printInfo('Index already exists - skipping');
            }
        }
        
        printSuccess('Database migrations completed successfully');
        await connection.end();
        return true;
    } catch (error) {
        printError(`Migration failed: ${error.message}`);
        
        if (error.code === 'ER_NO_SUCH_TABLE') {
            printWarning('Movies table does not exist!');
            printInfo('Please create the movies table first or import the SQL dump');
        }
        
        return false;
    }
}

// Step 6: Seed sample data
async function seedSampleData() {
    printStep(6, 'Checking for sample data...');
    
    require('dotenv').config();
    const mysql = require('mysql2/promise');
    
    try {
        const connection = await mysql.createConnection({
            host: process.env.DB_HOST || 'localhost',
            user: process.env.DB_USER || 'root',
            password: process.env.DB_PASSWORD || '',
            database: process.env.DB_NAME || 'sinhbtve_cinedrive'
        });
        
        // Check if movies table has data
        const [rows] = await connection.query('SELECT COUNT(*) as count FROM movies');
        const movieCount = rows[0].count;
        
        if (movieCount > 0) {
            printSuccess(`Movies table already has ${movieCount} records - skipping seed`);
            await connection.end();
            return true;
        }
        
        printWarning('Movies table is empty. Would you like to add sample data?');
        const answer = await prompt(`${colors.yellow}Add sample movies? (y/n)${colors.reset} [y]: `);
        
        if (answer.toLowerCase() === 'n' || answer.toLowerCase() === 'no') {
            printInfo('Skipping sample data seed');
            await connection.end();
            return true;
        }
        
        printInfo('Inserting sample movie data...');
        
        const sampleMovies = [
            {
                title: 'Inception',
                description: 'A thief who steals corporate secrets through dream-sharing technology.',
                video_url: '1234567890', // Replace with actual Facebook video ID
                poster: 'inception.jpg',
                genre: 'Sci-Fi',
                duration: '148',
                release_year: '2010',
                rating: '8.8'
            },
            {
                title: 'The Dark Knight',
                description: 'When the menace known as the Joker wreaks havoc on Gotham.',
                video_url: '9876543210', // Replace with actual Facebook video ID
                poster: 'dark-knight.jpg',
                genre: 'Action',
                duration: '152',
                release_year: '2008',
                rating: '9.0'
            },
            {
                title: 'Interstellar',
                description: 'A team of explorers travel through a wormhole in space.',
                video_url: '5555555555', // Replace with actual Facebook video ID
                poster: 'interstellar.jpg',
                genre: 'Sci-Fi',
                duration: '169',
                release_year: '2014',
                rating: '8.6'
            }
        ];
        
        for (const movie of sampleMovies) {
            await connection.query(`
                INSERT INTO movies (title, description, video_url, poster, genre, duration, release_year, rating, views)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, 0)
            `, [
                movie.title,
                movie.description,
                movie.video_url,
                movie.poster,
                movie.genre,
                movie.duration,
                movie.release_year,
                movie.rating
            ]);
            
            printSuccess(`Added: ${movie.title}`);
        }
        
        printSuccess(`Seeded ${sampleMovies.length} sample movies`);
        printWarning('Note: Update video_url with real Facebook video IDs for scraping to work');
        
        await connection.end();
        return true;
    } catch (error) {
        printError(`Seeding failed: ${error.message}`);
        
        if (error.code === 'ER_NO_SUCH_TABLE') {
            printWarning('Movies table does not exist!');
            printInfo('Please create the movies table first or import the SQL dump');
        }
        
        return false;
    }
}

// Step 7: Start the server
function startServer() {
    printStep(7, 'Starting the server...');
    
    printInfo('Server will start on port ' + (process.env.PORT || 3000));
    printSuccess('Setup completed successfully!');
    
    console.log(`\n${colors.green}${colors.bold}╔════════════════════════════════════════════════════════════════════╗${colors.reset}`);
    console.log(`${colors.green}${colors.bold}║  🎉 CineDrive Backend Setup Complete!                             ║${colors.reset}`);
    console.log(`${colors.green}${colors.bold}╚════════════════════════════════════════════════════════════════════╝${colors.reset}\n`);
    
    printInfo('Starting server in 3 seconds...');
    
    setTimeout(() => {
        try {
            execSync('npm start', {
                cwd: __dirname,
                stdio: 'inherit'
            });
        } catch (error) {
            printError('Failed to start server');
            console.error(error.message);
            process.exit(1);
        }
    }, 3000);
}

// Main setup function
async function runSetup() {
    console.log(`\n${colors.bold}${colors.blue}╔════════════════════════════════════════════════════════════════════╗${colors.reset}`);
    console.log(`${colors.bold}${colors.blue}║           CineDrive Backend Setup Wizard                           ║${colors.reset}`);
    console.log(`${colors.bold}${colors.blue}║           Automated Installation & Configuration                   ║${colors.reset}`);
    console.log(`${colors.bold}${colors.blue}╚════════════════════════════════════════════════════════════════════╝${colors.reset}\n`);
    
    try {
        // Step 1: Check Node.js version
        if (!checkNodeVersion()) {
            rl.close();
            process.exit(1);
        }
        console.log('');
        
        // Step 2: Install dependencies
        if (!installDependencies()) {
            rl.close();
            process.exit(1);
        }
        console.log('');
        
        // Step 3: Create .env file
        if (!await createEnvFile()) {
            rl.close();
            process.exit(1);
        }
        
        // Step 4: Test MySQL connection
        if (!await testMySQLConnection()) {
            rl.close();
            process.exit(1);
        }
        console.log('');
        
        // Step 5: Run migrations
        if (!await runMigrations()) {
            printWarning('Migrations failed, but continuing...');
        }
        console.log('');
        
        // Step 6: Seed sample data
        if (!await seedSampleData()) {
            printWarning('Seeding failed, but continuing...');
        }
        console.log('');
        
        // Close readline interface
        rl.close();
        
        // Step 7: Start server
        startServer();
        
    } catch (error) {
        printError('Setup failed with error:');
        console.error(error);
        rl.close();
        process.exit(1);
    }
}

// Handle graceful shutdown
process.on('SIGINT', () => {
    console.log('\n\nSetup interrupted by user');
    rl.close();
    process.exit(0);
});

// Run setup
runSetup();
